### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by nellatuulikki** [nuclearkittens/tiralabra-jpeg#1]
The repository was cloned on 3/12/2022 at 8 am.

## Testing the software 

The repository didn’t have any user instructions (though I think it has not been required yet to add it), so I tried to run this software using poetry instructions from Ohjelmistekniikka course.  

I’m getting the following error after running poetry invoke start. 

File "src/index.py", line 5, in <module> 

import core.util as util 

ModuleNotFoundError: No module named 'core' 

Seems that core.util library couldn’t be found. I tried running software manually in VSCode, but I got the same error there. I also tried to install the package with poetry add core.util, poetry add core, pip install core and pip install core.util but neither worked. After some time I figured it out, that there is actually python file called util.py under jpeg directory. I replaced the core with jpeg and the software started working.  

## Code quality  

The code quality checks seemed to be performed with pylint. I ran command python run invoke lint and the code was rated at 1.74/10. Pylint is mostly complaining about invalid naming and undefined variables. I noticed that code quality is checked also from test files.  Atleast in the Ohjelmistotekniikka course, we removed test out from code quality checking by creating .pylintrc file (https://ohjelmistotekniikka-hy.github.io/python/viikko4#pylint-ja-koodin-laaduun-staattinen-analyysi). 

I think code itself is very easy to ready and functions are good sized. Overall docstrings are very informative, but some of the functions are missing docstring (however, I think the code should be 100% commented right now 😊). Also, I really enjoyed your compact but informative style of naming functions (I need to learn that as well).  

However, it seems there is no actually usage of main() function in index.py. I would rather move the code under 

 if __name__ == '__main__':   

To main(). Also, I would remove all deactived printing calls. Now the index.py looks little bit messy. 

## Testing tests 

It seems that image.py is the only file that is being tested. Unfortunately, none of the tests were successful. The most frequent error in the tests were NameError: name 'Image' is not defined.  

## Structure 

Repository has a clear structure and there were no unnecessary files in the repository.

**Comment by nuclearkittens** [comment]
Thanks for the review, and catching some issues I hadn't noticed!

(I know that we are not required to reply to the code reviews/issues, so ignore this if you will – the reply is mostly for my own sake.)

Module import error in `index.py` is fixed, as is linting – I had completely forgotten to include the rc file, so million thanks for noticing (:

The main module was still a mess, as I've been using it for testing purposes instead of running a functioning app – maybe I should have clarified that somewhere. Mostly cleared up the structure now and removed all obsolete print statements etc.

Tests were probably failing since the functionality was moved to the utilities module but tests weren't, hence the name error (from not importing PIL in the original module). Easy fix, tests are moved where they should be.
